### PR TITLE
Emit XML documentation file

### PR DESCRIPTION
**Pull request by silkfire**
1. **Emit XML documentation file**

   The XML documentation file is not set to be emitted upon publishing the package, leading to comments not being shown in IntelliSense when using the NuGet package.
2. **Complete XML comments on classes / methods**

    Some methods and classes were missing comments; the documentation should cover the entire public API now.
3.  **Explicitly expose internal classes to the unit test assembly**

    The `ExceptionTranslatorRequestMiddleware` class had a sole `internal` constructor but could not be made internal because the unit tests wouldn't be able to test the class. There's a way to have it be internal but only exposing it to the unit test assembly, making sure other consumers of the library won't be able to access the class.
4. **Provided dictionary for default headers shouldn't be restricted to being read-only**

    For some reason, the `WithDefaultHeaders` method accepted a parameter of type `IReadOnlyDictionary<,>`. This is quite restrictive and has been changed to a much more inclusive `IDictionary<,>`.
5. **Hid a few internal files.**

    A few files are not really related to the project so can be hidden in the Solution Explorer.
    
6. **Bumped package version to 2.1.3.**

### CODE REVIEW

**Comment by silkfire** [comment]
I'm not sure why the pipeline triggers 8 warnings for the same line; but the specific static class doesn't need any XML comment because it only has extension methods.

**Comment by silkfire** [comment]
@myarichuk Have you had some time to look at the PR?

**Comment by silkfire** [comment]
Trying to grab your attention @myarichuk again, are you ready to close this PR?

**Comment by myarichuk** [comment]
Apologies, had a quite  busy couple of weeks...

**Comment by myarichuk** [comment]
note that the nuget related CI/CD pipeline shouldn't be working yet, still need to make it work properly

**Comment by myarichuk** [comment]
And also, huge thanks again for your contribution! Hopefully this project is useful for you :)

**Comment by silkfire** [comment]
No worries. I figured that could be the case-- I think that's it for now. We have a working version that I think lives up to the standards of a high quality lib. Thanks for accepting my chain of PRs.

I hope you'll be able to solve the CI/CD pipeline some time in the future, let me know if you need some assistance or just general advice. And thanks for releasing this latest version to NuGet :)

**Pull request merged**
