### PR TITLE
Add a method to configure the primary message handler while building the client factory

### PR DESCRIPTION
**Pull request by silkfire**
1. **Add a method to configure the primary message handler while building the client factory**

   It is currently only possible to configure the primary message handler (`SocketsHttpHandler`/`HttpClientHandler`) while building the client, but not while constructing the factory. This is a limitation because the user might perhaps want a factory that produces clients with the primary message handler configured in a specific way. See `IHttpClientBuilder.WithPrimaryMessageHandlerConfigurator()`.

2. **Tidy XML comments**

    Cleaned up the language in all XML comments to aspire to general correctness and consistency throughout the library.

3. **Improve unit test coverage to 100%**

    Re-evaluated all tests in order to attain 100% test coverage. Removed a few untestable code lines with guards. Made sure all branches were visited by adding new tests and revising existing ones.

4. **Clarify overload usage**

    In some cases the usage of an overload of a method could be ambiguous. To remedy this, a more specific overload was added. In a few instances, an extra overload has been added to improve the quality of life for the library consumer.

All in all, no intrinsic functionality has been altered. The tests should be able to verify this.

### CODE REVIEW

**Comment by silkfire** [comment]
@myarichuk It seems as if the .NET472 tests aren't being run in Travis. Have they been temporarily turned off?

**Comment by myarichuk** [comment]
Thanks a lot for this PR!

As to .Net 4.7 tests not running in Travis - I think that is because at the moment Travis is configured to run tests in Linux VM. 
I am considering moving the build to Github Actions as it supports windows based workflows and has better support for C# overall.

**Comment by myarichuk** [comment]
(Until I migrate to Github Actions I will publish a new version manually)

**Comment by silkfire** [comment]
Glad you liked changes! It might have been a bit overkill to put it all in one PR but I was a bit on a roll, actually. I think I got two more PRs coming up, but they will be very small and don't change any functionality either.

**Pull request merged**
